Queens of the Stone Age Store/Models/Clothing.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Queens_of_the_Stone_Age_Store.Models
{
    public class Clothing
    {
        public int Clothing_ID { get; set; }
        public string TypeOFClothing { get; set; }
        public string ClothingDescription { get; set; }
        public string Sizes { get; set; }
        public decimal ClothingPrice { get; set; }
        public string ClothingName { get; set; }
        public int ClothingQuantity { get; set; }
    }
}

Queens of the Stone Age Store/Models/ClothingViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Queens_of_the_Stone_Age_Store.Models
{
    public class ClothingViewModel
    {
        public Clothing SingleClothing { get; set; }
        public List<Clothing> ClothingList { get; set; }
        public ClothingViewModel()
        {
            SingleClothing = new Clothing();
            ClothingList = new List<Clothing>();
        }
    }
}

Queens of the Stone Age Store/Controllers/ClothingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Queens_of_the_Stone_Age_Store.Models;
using DAL;
using DAL.Objects;

namespace Queens_of_the_Stone_Age_Store.Controllers
{
    public class ClothingController : Controller
    {
        static Mapper _mapper = new Mapper();
        static ClothingDataAccess _ClothingDataAccess = new ClothingDataAccess();
        [HttpGet]
        public ActionResult ClothingView()
        {
            ClothingViewModel _ViewModelClothing = new ClothingViewModel();
            _ViewModelClothing.ClothingList = _mapper.ClothingMap(_ClothingDataAccess.GetAllClothing());
            return View(_ViewModelClothing);
        }
        public ActionResult DeleteClothing (int Delete_Clothing)
        {
            if ((int)Session["Role_ID"] == 3)
            {
                clothingDAO _DeleteClothing = new clothingDAO();
                _DeleteClothing.Clothing_ID = Delete_Clothing;
                _ClothingDataAccess.DeleteClothing(_DeleteClothing);
            }
            return RedirectToAction("ClothingView");
        }
        [HttpPost]
        public ActionResult CreateClothing(Clothing newClothing)
        {
            if ((int)Session["Role_ID"] == 3 || (int)Session["Role_ID"] == 2)
            {
                clothingDAO ClothingToCreate = _mapper.SingleClothing(newClothing);
                _ClothingDataAccess.CreateClothing(ClothingToCreate);
            }
            return RedirectToAction("ClothingView");
        }
        [HttpPost]
        public ActionResult UpdateClothing(Clothing _ClothingInfo)
        {
            if ((int)Session["Role_ID"] == 3 || (int)Session["Role_ID"] == 2)
            {
                clothingDAO _recievedClothing = _mapper.SingleClothing(_ClothingInfo);
                _ClothingDataAccess.UpdateClothing(_recievedClothing);
                return RedirectToAction("ClothingView");
            }
            return RedirectToAction("ClothingView");
        }
        public ActionResult GetClothingID(int _GetID)
        {
            shoppingcartDAO cartToGet = new shoppingcartDAO();
            cartToGet.Clothing_ID = _GetID;
            cartToGet.User_ID = (int)Session["User_ID"];
            _ClothingDataAccess.GetClothingID(cartToGet);
            return RedirectToAction("ClothingView");
        }
        public ActionResult SendClothingID(int _SendID)
        {
            shoppingcartDAO cartToSend = new shoppingcartDAO();
            cartToSend.Clothing_ID = _SendID;
            cartToSend.User_ID = (int)Session["User_ID"];
            _ClothingDataAccess.SendClothingID(cartToSend);
            return RedirectToAction("ClothingView");
        }

    }
}

Queens of the Stone Age Store/Views/Clothing/ClothingView.cshtml
@model Queens_of_the_Stone_Age_Store.Models.ClothingViewModel
@using Queens_of_the_Stone_Age_Store.Models
@{
    ViewBag.Title = "ClothingView";
}

<h2>ClothingView</h2>
<table class="table table-striped">
    <tr>
        <th>Type OF Clothing</th>
        <th>Clothing Description</th>
        <th>Sizes</th>
        <th>Clothing Price</th>
        <th>Clothing Name</th>
        <th>Delete</th>
        <th>Update</th>
    </tr>
    @foreach (Clothing _ClothingInfo in Model.ClothingList)
    {
    <tr>
        @using (Html.BeginForm("UpdateClothing", "Clothing", FormMethod.Post))
        {
            @Html.HiddenFor(model => _ClothingInfo.Clothing_ID)
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => _ClothingInfo.TypeOFClothing, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => _ClothingInfo.TypeOFClothing, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => _ClothingInfo.ClothingDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => _ClothingInfo.ClothingDescription, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => _ClothingInfo.Sizes, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => _ClothingInfo.Sizes, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => _ClothingInfo.ClothingPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => _ClothingInfo.ClothingPrice, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => _ClothingInfo.ClothingName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => _ClothingInfo.ClothingName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            @Html.HiddenFor(model => _ClothingInfo.ClothingQuantity, new { htmlAttributes = new { @class = "form-control" } })                      
            <td>
                @Html.ActionLink("Delete", "DeleteClothing", new { Delete_Clothing = _ClothingInfo.Clothing_ID }, new { @class = "btn btn-danger" })
                @Html.ActionLink("Send to cart", "SendClothingID", new { _SendID = _ClothingInfo.Clothing_ID }, new { @class = "btn btn-danger" })
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Update" class="btn btn-info" />
                    </div>
                </div>
            </td>
        }
    </tr>
    }
    <tr>
        @{ Clothing newClothing = new Clothing();}
        @using (Html.BeginForm("CreateClothing", "Clothing", FormMethod.Post))
        {
            @Html.HiddenFor(model => newClothing.Clothing_ID)
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => newClothing.TypeOFClothing, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => newClothing.TypeOFClothing, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => newClothing.ClothingDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => newClothing.ClothingDescription, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => newClothing.Sizes, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => newClothing.Sizes, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => newClothing.ClothingPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => newClothing.ClothingPrice, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => newClothing.ClothingName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => newClothing.ClothingName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
                        @Html.HiddenFor(model => newClothing.ClothingQuantity, new { htmlAttributes = new { @class = "form-control" } })                    
            <td>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-info" />
                    </div>
                </div>
            </td>
        }
    </tr>
</table>