Queens of the Stone Age Store/Models/BandMembers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Queens_of_the_Stone_Age_Store.Models
{
    public class BandMembers
    {
        public int BandMembers_ID { get; set; }
        public string MemberName { get; set; }
        public string MemberBio { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string BirthLocation { get; set; }
    }
}

Queens of the Stone Age Store/Models/BandMembersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Queens_of_the_Stone_Age_Store.Models
{
    public class BandMembersViewModel
    {
        public BandMembers SingleMember { get; set; }
        public List<BandMembers> MembersList { get; set; }
        public BandMembersViewModel()
        {
            SingleMember = new BandMembers();
            MembersList = new List<BandMembers>();
        }
    }
}

Queens of the Stone Age Store/Controllers/BandMemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Queens_of_the_Stone_Age_Store.Models;
using DAL;
using DAL.Objects;

namespace Queens_of_the_Stone_Age_Store.Controllers
{
    public class BandMemberController : Controller
    {
        static Mapper _mapper = new Mapper();
        static BandMemberDataAccess _BandMemberDataAccess = new BandMemberDataAccess();
        [HttpGet]
        public ActionResult BandMemberView()
        {
            BandMembersViewModel _ViewModelBandMember = new BandMembersViewModel();
            _ViewModelBandMember.MembersList = _mapper.MemeberMap(_BandMemberDataAccess.GetAllMembers());
            return View(_ViewModelBandMember);
        }
        public ActionResult DeleteMember(int Delete_Member)
        {
            if ((int)Session["Role_ID"] == 3)
            {
                bandmembersDAO _DeleteMember = new bandmembersDAO();
                _DeleteMember.BandMembers_ID = Delete_Member;
                _BandMemberDataAccess.DeleteMember(_DeleteMember);
            }
            return RedirectToAction("BandMemberView");
        }
        [HttpPost]
        public ActionResult CreateMember(BandMembers newMember)
        {
            if ((int)Session["Role_ID"] == 3 || (int)Session["Role_ID"] == 2)
            {
                bandmembersDAO MemberToCreate = _mapper.SingleMember(newMember);
                _BandMemberDataAccess.CreateMember(MemberToCreate);
            }
            return RedirectToAction("BandMemberView");
        }
        [HttpPost]
        public ActionResult UpdateMember(BandMembers _MemberInfo)
        {
            if ((int)Session["Role_ID"] == 3 || (int)Session["Role_ID"] == 2)
            {
                bandmembersDAO _recievedMember = _mapper.SingleMember(_MemberInfo);
                _BandMemberDataAccess.UpdateMember(_recievedMember);
            }
            return RedirectToAction("BandMemberView");
        }
    }
}

Queens of the Stone Age Store/Views/BandMember/BandMemberView.cshtml
@model Queens_of_the_Stone_Age_Store.Models.BandMembersViewModel
@using Queens_of_the_Stone_Age_Store.Models
@{
    ViewBag.Title = "BandMemberView";
}

<h2>BandMemberView</h2>
<table class="table table-striped">
    <tr>
        <th>MemberName</th>
        <th>MemberBio</th>
        <th>DateOfBirth</th>
        <th>BirthLocation</th>
    </tr>
    @foreach (BandMembers _MemberInfo in Model.MembersList)
    {
    <tr>
        @using (Html.BeginForm("UpdateMember", "BandMember", FormMethod.Post))
        {
            @Html.HiddenFor(model => _MemberInfo.BandMembers_ID)
            
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => _MemberInfo.MemberName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => _MemberInfo.MemberName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => _MemberInfo.MemberBio, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => _MemberInfo.MemberBio, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => _MemberInfo.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => _MemberInfo.DateOfBirth, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => _MemberInfo.BirthLocation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => _MemberInfo.BirthLocation, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                @Html.ActionLink("Delete", "DeleteMember", new { Delete_Member = _MemberInfo.BandMembers_ID }, new { @class = "btn btn-danger" })
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Update" class="btn btn-info" />
                    </div>
                </div>
            </td>
         }
         </tr>      
    }
    <tr>
        @{ BandMembers newMember = new BandMembers();}
        @using (Html.BeginForm("CreateMember", "BandMember", FormMethod.Post))
        {
            @Html.HiddenFor(model => newMember.BandMembers_ID)
           
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => newMember.MemberName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => newMember.MemberName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => newMember.MemberBio, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => newMember.MemberBio, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => newMember.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => newMember.DateOfBirth, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => newMember.BirthLocation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => newMember.BirthLocation, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                @Html.ActionLink("???", "DeleteMember", new { Delete_Member = newMember.BandMembers_ID }, new { @class = "btn btn-danger" })
            </td>
            <td>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-info" />
                    </div>
                </div>
            </td>
        }
    </tr>
</table>